In [12]:
import pandas as pd
df = pd.read_excel(r"C:\Users\User\Downloads\Telegram Desktop\Реестр2.xlsx")
df

,№ п/п,Наименование / ФИО,Тип субъекта,Категория,ОГРН,ИНН,Основной вид деятельности,Регион,Район,Город,...,Дата исключения из реестра,Телефон,E-mail,WWW,Наличие лицензий,"Наличие заключенных договоров, контрактов","Производство инновационной, высокотехнологичной продукции",Участие в программах партнерства,Является социальным предприятием,Среднесписочная численность работников за предшествующий календарный год
0,20,"""КОРПОРАЦИЯ ВИТ"" (ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕ...",Юридическое лицо,Малое предприятие,1025004907080,5038038838,41.20 Строительство жилых и нежилых зданий,50 - Московская область,Пушкино г,NaN,...,NaN,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,36.0
1,25,"""ЛАВИНА"" ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ",Юридическое лицо,Малое предприятие,1035010952624,5027064258,41.2 Строительство жилых и нежилых зданий,50 - Московская область,NaN,г Люберцы,...,NaN,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,40.0
2,52,"""ХОЗРАСЧЕТНАЯ СТРОИТЕЛЬНО-ТЕХНОЛОГИЧЕСКАЯ ФИРМ...",Юридическое лицо,Среднее предприятие,1025007270551,5027006369,41.20 Строительство жилых и нежилых зданий,50 - Московская область,NaN,г Дзержинский,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,201.0
3,4651,"АКЦИОНЕРНОЕ ОБЩЕСТВО ""2МЕН ГРУПП ДЕВЕЛОПМЕНТ""",Юридическое лицо,Малое предприятие,1067746424899,7701651356,41.2 Строительство жилых и нежилых зданий,72 - Тюменская область,NaN,г Тюмень,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,19.0
4,4653,"АКЦИОНЕРНОЕ ОБЩЕСТВО ""777""",Юридическое лицо,Малое предприятие,1021400692048,1414006922,41.20 Строительство жилых и нежилых зданий,77 - г.Москва,NaN,NaN,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10698,560903,СОВМЕСТНОЕ ПРЕДПРИЯТИЕ ОБЩЕСТВО С ОГРАНИЧЕННОЙ...,Юридическое лицо,Среднее предприятие,1026500785673,6504043928,41.20 Строительство жилых и нежилых зданий,65 - Сахалинская область,Корсаковский р-н,г Корсаков,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,145.0
10699,565172,СТРОИТЕЛЬНО-ИНВЕСТИЦИОННАЯ КОМПАНИЯ ОБЩЕСТВО С...,Юридическое лицо,Малое предприятие,1032307179409,2312105041,41.2 Строительство жилых и нежилых зданий,23 - Краснодарский край,NaN,г Краснодар,...,NaN,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,16.0
10700,576233,"УПРАВЛЕНИЕ МЕХАНИЗИРОВАННЫХ РАБОТ "" КАСКАД "" (...",Юридическое лицо,Малое предприятие,1022300509637,2301032458,41.2 Строительство жилых и нежилых зданий,23 - Краснодарский край,Анапский р-н,NaN,...,NaN,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,24.0
10701,580133,"ФИРМА ""ТЕПЛОСТРОЙПРОЕКТ-С"" ОБЩЕСТВО С ОГРАНИЧЕ...",Юридическое лицо,Малое предприятие,1032000400233,2002001476,41.20 Строительство жилых и нежилых зданий,20 - Чеченская Республика,Ачхой-Мартановский р-н,NaN,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,67.0
10702,580135,"ФИРМА ""Ц.М.ХОЛДИНГ"" ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТ...",Юридическое лицо,Малое предприятие,1020700539640,702005585,41.20 Строительство жилых и нежилых зданий,07 - Кабардино-Балкарская Республика,Зольский р-н,NaN,...,NaN,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,11.0

In [13]:
df_clean = df[df['Основной вид деятельности'] == '41.20 Строительство жилых и нежилых зданий']
df_clean

,№ п/п,Наименование / ФИО,Тип субъекта,Категория,ОГРН,ИНН,Основной вид деятельности,Регион,Район,Город,...,Дата исключения из реестра,Телефон,E-mail,WWW,Наличие лицензий,"Наличие заключенных договоров, контрактов","Производство инновационной, высокотехнологичной продукции",Участие в программах партнерства,Является социальным предприятием,Среднесписочная численность работников за предшествующий календарный год
0,20,"""КОРПОРАЦИЯ ВИТ"" (ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕ...",Юридическое лицо,Малое предприятие,1025004907080,5038038838,41.20 Строительство жилых и нежилых зданий,50 - Московская область,Пушкино г,NaN,...,NaN,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,36.0
2,52,"""ХОЗРАСЧЕТНАЯ СТРОИТЕЛЬНО-ТЕХНОЛОГИЧЕСКАЯ ФИРМ...",Юридическое лицо,Среднее предприятие,1025007270551,5027006369,41.20 Строительство жилых и нежилых зданий,50 - Московская область,NaN,г Дзержинский,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,201.0
4,4653,"АКЦИОНЕРНОЕ ОБЩЕСТВО ""777""",Юридическое лицо,Малое предприятие,1021400692048,1414006922,41.20 Строительство жилых и нежилых зданий,77 - г.Москва,NaN,NaN,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,35.0
5,4668,"АКЦИОНЕРНОЕ ОБЩЕСТВО ""АГРОТЕХИМПОРТ""",Юридическое лицо,Малое предприятие,1043301806415,3327332190,41.20 Строительство жилых и нежилых зданий,33 - Владимирская область,NaN,г Владимир,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,52.0
6,4674,"АКЦИОНЕРНОЕ ОБЩЕСТВО ""АКС""",Юридическое лицо,Малое предприятие,1027807999988,7816061297,41.20 Строительство жилых и нежилых зданий,78 - г.Санкт-Петербург,NaN,NaN,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10696,560512,"СМУ ""МОНОЛИТ"" (ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТ...",Юридическое лицо,Малое предприятие,1162301050515,2301091157,41.20 Строительство жилых и нежилых зданий,23 - Краснодарский край,Анапский р-н,г Анапа,...,NaN,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,4.0
10697,560513,"СМУ ""РУСЬ"" (ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕН...",Юридическое лицо,Малое предприятие,1132301002900,2301083597,41.20 Строительство жилых и нежилых зданий,23 - Краснодарский край,Анапский р-н,г Анапа,...,NaN,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,74.0
10698,560903,СОВМЕСТНОЕ ПРЕДПРИЯТИЕ ОБЩЕСТВО С ОГРАНИЧЕННОЙ...,Юридическое лицо,Среднее предприятие,1026500785673,6504043928,41.20 Строительство жилых и нежилых зданий,65 - Сахалинская область,Корсаковский р-н,г Корсаков,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,145.0
10701,580133,"ФИРМА ""ТЕПЛОСТРОЙПРОЕКТ-С"" ОБЩЕСТВО С ОГРАНИЧЕ...",Юридическое лицо,Малое предприятие,1032000400233,2002001476,41.20 Строительство жилых и нежилых зданий,20 - Чеченская Республика,Ачхой-Мартановский р-н,NaN,...,NaN,NaN,NaN,NaN,Да,Нет,Нет,Нет,Нет,67.0
10702,580135,"ФИРМА ""Ц.М.ХОЛДИНГ"" ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТ...",Юридическое лицо,Малое предприятие,1020700539640,702005585,41.20 Строительство жилых и нежилых зданий,07 - Кабардино-Балкарская Республика,Зольский р-н,NaN,...,NaN,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,11.0

In [16]:
import requests
from pypdf import PdfReader
import re
from io import BytesIO
import time
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/json"
})
def get_org_id(inn):
    
    res = session.get(
        f"https://bo.nalog.gov.ru/advanced-search/organizations/search"
        f"?query={inn}&page=0"
    ).json()
    
    if not res["content"]:
        return None
    
    return res["content"][0]["id"]
def get_bfo(org_id):
    
    res = session.get(
        f"https://bo.nalog.gov.ru/nbo/organizations/{org_id}/bfo/"
    ).json()
    
    return res
def get_company_data(inn):
    
    org_id = get_org_id(inn)
    
    if org_id is None:
        return None
    
    bfo = get_bfo(org_id)
    
    return bfo
def get_report_text(org_id, year, correction):
    
    clarification_id = None
    
    if correction.get("clarification"):
        clarification_id = correction["clarification"].get("id")
    
    if clarification_id:
        
        url = f"https://bo.nalog.gov.ru/download/clarification/{clarification_id}"
        
        response = session.get(url, timeout=60)
        
        if response.status_code == 200 and response.content.startswith(b"%PDF"):
            
            pdf = PdfReader(
                BytesIO(response.content),
                strict=False
            )
            
            text = ""
            
            for page in pdf.pages:
                page_text = page.extract_text()
                if page_text:
                    text += page_text + "\n"
            
            return text
    
    correction_id = correction["id"]
    
    url = (
        f"https://bo.nalog.gov.ru/download/bfo/pdf/"
        f"{org_id}?period={year}&detailId={correction_id}"
    )
    
    response = session.get(url, timeout=60)
    
    if response.status_code == 200 and response.content.startswith(b"%PDF"):
        
        pdf = PdfReader(
            BytesIO(response.content),
            strict=False
        )
        
        text = ""
        
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
        
        return text
    
    return ""
def get_nma_amortization(text, year):

    lines = text.splitlines()

    start = None

    for i, line in enumerate(lines):
        if "наличие и движение нематериальных активов" in line.lower():
            start = i
            break

    if start is None:
        return None

    for line in lines[start:start + 150]:

        match = re.search(
            rf"за\s+{year}\s*г\.\s*(.*)",
            line,
            re.IGNORECASE
        )

        if not match:
            continue

        values_text = match.group(1)

        numbers = re.findall(
            r'\(?-?\d[\d\s]*(?:[,.]\d+)?\)?',
            values_text
        )

        if len(numbers) >= 3:

            value = numbers[2]

            value = value.replace(" ", "")
            value = value.replace(",", ".")

            if value.startswith("(") and value.endswith(")"):
                value = value[1:-1]

            try:
                return abs(float(value))
            except:
                return None

    return None

In [26]:
def get_company_data(inn):

    org_id = get_org_id(inn)

    if org_id is None:
        return []

    bfo = get_bfo(org_id)

    results = []

    reports = {}

    for period_data in bfo:

        year = int(period_data["period"])

        annual_list = [
            x for x in period_data["typeCorrections"]
            if x["type"] == 12
        ]

        if not annual_list:
            continue

        correction = annual_list[0]["correction"]

        text = get_report_text(
            org_id,
            year,
            correction
        )

        reports[year] = {
            "correction": correction,
            "text": text
        }
    for year, report in reports.items():

        correction = report["correction"]
        text = report["text"]

        financial_result = correction["financialResult"]

        profit_before_tax = financial_result.get("current2300")
        interest_expense = financial_result.get("current2330")

        # Амортизация НМА из отчёта этого года
        amortization_nma = get_nma_amortization(
            text,
            year
        )
        if amortization_nma is None:

            next_year = year + 1

            if next_year in reports:

                next_text = reports[next_year]["text"]

                amortization_nma = get_nma_amortization(
                    next_text,
                    year
                )
        if (
            profit_before_tax is not None
            and interest_expense is not None
            and amortization_nma is not None
        ):

            ebita = (
                profit_before_tax
                + abs(interest_expense)
                + abs(amortization_nma)
            )

        else:
            ebita = None

        results.append({
            "ИНН": inn,
            "Год": year,
            "Прибыль до налогообложения": profit_before_tax,
            "Проценты к уплате": abs(interest_expense) if interest_expense is not None else None,
            "Амортизация НМА": amortization_nma,
            "EBITA": ebita
        })

    return results

In [19]:
inn = str(df["ИНН"].iloc[0])
result = get_company_data(inn)
test_df = pd.DataFrame(result)
test_df

,ИНН,Год,Прибыль до налогообложения,Проценты к уплате,Амортизация НМА,EBITA
0,5038038838,2023,-20665.0,3334.0,NaN,NaN
1,5038038838,2021,3430.0,5601.0,NaN,NaN
2,5038038838,2024,-19938.0,1521.0,5.0,-18412.0
3,5038038838,2022,20219.0,141.0,NaN,NaN
4,5038038838,2025,-457.0,11869.0,5.0,11417.0

In [27]:
all_data = []

for inn in df["ИНН"].dropna().unique():
    result = get_company_data(str(inn))

    for row in result:
        all_data.append(row)

data_df = pd.DataFrame(all_data)

data_df = data_df.drop(columns=["EBITA"], errors="ignore")

data_df = data_df.sort_values(
    ["ИНН", "Год"]
).reset_index(drop=True)

data_df

Multiple definitions in dictionary at byte 0x3459d6 for key /Info
Multiple definitions in dictionary at byte 0x3459e3 for key /Info
Multiple definitions in dictionary at byte 0x3459f0 for key /Info
Multiple definitions in dictionary at byte 0x44e141 for key /Info
Multiple definitions in dictionary at byte 0x44e14e for key /Info
Multiple definitions in dictionary at byte 0x44e15b for key /Info
Multiple definitions in dictionary at byte 0x75c873 for key /Info
Multiple definitions in dictionary at byte 0x75c880 for key /Info
Multiple definitions in dictionary at byte 0x75c88d for key /Info
Multiple definitions in dictionary at byte 0x56cf9d for key /Info
Multiple definitions in dictionary at byte 0x56cfaa for key /Info
Multiple definitions in dictionary at byte 0x56cfb7 for key /Info
Multiple definitions in dictionary at byte 0x3594d4 for key /Info
Multiple definitions in dictionary at byte 0x3594e1 for key /Info
Multiple definitions in dictionary at byte 0x3594ee for key /Info
Multiple definitions in dictionary at byte 0x49e401 for key /Info
Multiple definitions in dictionary at byte 0x49e40e for key /Info
Multiple definitions in dictionary at byte 0x49e41b for key /Info
Multiple definitions in dictionary at byte 0x1b42d9 for key /Info
Multiple definitions in dictionary at byte 0x1b42e6 for key /Info
Multiple definitions in dictionary at byte 0x1b42f3 for key /Info

ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None)", ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))